//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuckXingShiZhengCe.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuckXingShiZhengCe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon qb1 {
            get {
                object obj = ResourceManager.GetObject("qb1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon qb9 {
            get {
                object obj = ResourceManager.GetObject("qb9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Title_md5,Answer
        ///0051d4c909b052eb1117cff77514d8e4,0
        ///00d932ab3ba72e4e4bb0a5ab17bbae0b,1
        ///066dc33d54be5f04310cc73344dd43e3,1
        ///0ad8dacb65dea7c6e8846a248e9209e3,0
        ///0af194079e85bf8e2fb4699d306e7918,1
        ///150c2dca4a75e14baa2b2ece8fea93e5,0
        ///1b12b25b45a30dcf17f88d6a4a0058be,0
        ///1c217eeb0bb2d5124c002bc6a6ea7dec,0
        ///21669069c8ae64db3c4fd312cce883de,3
        ///21a906e35a12df790a12f5f3097a5cb8,1
        ///29c2eb24db5d064771adfcdf12484975,3
        ///2ae233ce269e68de0995fd5f0b1c3727,0
        ///2b149c40c11fbc758f135d35ca77534a,0
        ///2e83c7654ed1e94cbb4b394864 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tiku_txt {
            get {
                return ResourceManager.GetString("tiku_txt", resourceCulture);
            }
        }
    }
}
